// Generated by CoffeeScript 1.12.2
(function() {
  var spawn, utils;

  spawn = require('child_process').spawn;

  utils = require('./utils');

  exports.deleteSubvolAsync = function(subvol) {
    return utils.waitPidAsync(spawn('btrfs', ['subvolume', 'delete', subvol]));
  };

  exports.snapshotSubvolAsync = function(src, dest) {
    return utils.waitPidAsync(spawn('btrfs', ['subvolume', 'snapshot', src, dest]));
  };

}).call(this);
