// Generated by CoffeeScript 1.12.2
(function() {
  var Promise;

  Promise = require('bluebird');

  exports.waitPidAsync = function(ps) {
    return new Promise(function(resolve, reject) {
      return ps.on('error', reject).on('exit', function(code, signal) {
        var error;
        if (code !== 0) {
          error = new Error("rsync exited. code: " + code + " signal: " + signal);
          error.code = code;
          error.signal = signal;
          return reject(error);
        } else {
          return resolve();
        }
      });
    });
  };

}).call(this);
